@endpoint=/api/auth
### Login

post {{hostname}}{{endpoint}}/login
Content-Type: application/json

{
  "email": "amaldonadojuarez@gmail.com",
  "pswd": "123456"
}

### Validate token with header

get {{hostname}}/validate
Authorization: Bearer {{token}}
