@endpoint=/api/skills
### Create

post {{hostname}}{{endpoint}}
Content-Type: application/json

{
  "name": "JavaScript",
  "image": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png"
}

### All

get {{hostname}}{{endpoint}}

### Update one

put {{hostname}}{{endpoint}}
Content-Type: application/json

{
  "_id": "66b81a2723ad8551ecabe53a",
  "name": "otro",
  "image": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png"
}

### Delete one

delete {{hostname}}{{endpoint}}/66b81a2723ad8551ecabe53a
